name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downloading & Installing Essentials
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/gulshanhex/Redx/main/Download.bat" -OutFile "Download.bat"
          cmd /c Download.bat

      - name: Show Website
        shell: cmd
        run: show.bat

      - name: Time Counter
        shell: cmd
        run: loop.bat
